  
service: bz-commendation-backend

useDotenv: true

provider:
  name: aws
  iam:
    role: arn:aws:iam::177987852765:role/DynamoDBLambaRole
  environment:
    PORT: ${env:PORT}
    TWILIO_SID: ${env:TWILIO_SID}
    TWILIO_AUTH: ${env:TWILIO_AUTH}
    TWILIO_NUMBER: ${env:TWILIO_NUMBER}
    EMAIL: ${env:EMAIL}
    EMAIL_PASSWORD: ${env:EMAIL_PASSWORD}
    OAUTH_CLIENTID: ${env:OAUTH_CLIENTID}
    OAUTH_CLIENT_SECRET: ${env:OAUTH_CLIENT_SECRET}
    OAUTH_REFRESH_TOKEN: ${env:OAUTH_REFRESH_TOKEN}
  runtime: nodejs14.x
  stage: dev
  region: us-east-2
  memorySize: 512

plugins:
  - serverless-plugin-typescript
  - serverless-offline

functions:
  app:
    handler: src/app.handler
    events:
      - http: ANY /
      - http: ANY /{proxy+}