  
service: aws-node-rest-api-typescript

useDotenv: true

provider:
  name: aws
  iam:
    role: arn:aws:iam::069536840885:role/lambda-dynamo-acess
  runtime: nodejs14.x
  stage: dev
  region: us-east-2
  memorySize: 512

plugins:
  - serverless-plugin-typescript
  - serverless-offline

functions:
  app:
    handler: src/app.handler
    events:
      - http: ANY /
      - http: ANY /{proxy+}