openapi: 3.0.0
info:
  version: 1.0.0
  title: BZ Commendations API
  description: The API that describes the BZ Commendations backend.
paths:
  # Commendation paths.
  /commendation:
    get:
      description: Gets all commendations.
      deprecated: true
      security:
        - cookieAuth: []
      responses:
        200:
          description: A list of commendations.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Commendation"
    put:
      description: Updates a commendation
      security:
        - cookieAuth: []
      deprecated: true
      responses:
        200:
          description: A commendation has successfully been updated. UNIMPLEMENTED. DO NOT USE.
    post:
      description: Creates a commendation
      security:
        - cookieAuth: []
      responses:
        200:
          description: A correctly created commendation has been inserted.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Commendation"
  /commendation/user:
    get:
      description: Gets a user's commendation by email.
      security:
        - cookieAuth: []
      responses:
        200:
          description: One user's commendations.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Commendation"
    delete:
      description: Deletes a commendation
      security:
        - cookieAuth: []
      deprecated: true
      responses:
        200:
          description: Successfully deleted a commendation.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ItemCollectionMetrics"
  /commendation/admin:
    get:
      security:
        - cookieAuth: []
      responses:
        200:
          description: A list of commendations.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Commendation"
  /commendation/kiosk:
    post:
      description: Creates a commendation
      security:
        - cookieAuth: []
      responses:
        200:
          description: A correctly created commendation has been inserted.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Commendation"
  /checkAuth:
    get:
      responses:
        200:
          description: Checks if you are authenticated. Used for frontend auth.
  /checkAdmin:
    get:
      security:
        - cookieAuth: []
      responses:
        200:
          description: Checks if you are authenticated as an admin. Used for frontend auth.
  # Suggestions
  /suggestion:
    post:
      description: Creates a new suggestion.
      security:
        - cookieAuth: []
      responses:
        200:
          description: Returns the new suggestion
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Suggestion"



components:
  securitySchemes:
    cookieAuth:
      type: apiKey
      in: cookie
      name: AUTHORIZATION
  schemas:
    Error:
      type: object
      properties:
        message:
          type: string
        error:
          type: object
    Commendation:
      type: object
      required:
        - date
        - message
        - fromEmail
        - toEmail
        - otherEmails
        - phone
      properties:
        _id:
          type: string
        date:
          type: string
        message:
          type: string
        fromEmail:
          type: string
        toEmail:
          type: string
        otherEmails:
          type: array
          items:
            type: string
        phone:
          type: string
    Suggestion:
      type: object
      required:
        - date
        - message
        - fromEmail
        - toTeam
      properties:
        date:
          type: string
        message:
          type: string
        fromEmail:
          type: string
        toTeam:
          type: string
    ItemCollectionMetrics:
      type: object
      properties:
        ItemCollectionKey:
          type: array
          items:
            type: object
        SizeEstimateRangeGB:
          type: array
          items:
            type: integer

