version: '3'
services:
  db:
    image: mariadb
    restart: always
    ports:
      - 5036:3306
    volumes:
      - ./bz.sql:/docker-entrypoint-initdb.d/bz.sql
    environment:
      MYSQL_ROOT_PASSWORD: test
  adminer:
    image: adminer
    restart: always
    ports:
      - 9000:8080